"""empty message

Revision ID: d09f31d90362
Revises: ab6c182622bc
Create Date: 2023-04-04 20:24:30.904150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09f31d90362'
down_revision = 'ab6c182622bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('native_english_speaker', sa.String(length=100), nullable=True),
    sa.Column('course_instructor', sa.String(length=50), nullable=True),
    sa.Column('course', sa.String(length=200), nullable=True),
    sa.Column('semester', sa.String(length=10), nullable=True),
    sa.Column('class_size', sa.String(length=200), nullable=True),
    sa.Column('performance_score', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=800), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('students')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('city', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('addr', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('pin', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(length=800), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='students_pkey')
    )
    op.drop_table('ta')
    # ### end Alembic commands ###
