"""empty message

Revision ID: eb9a4b5d660d
Revises: d09f31d90362
Create Date: 2023-04-05 00:56:37.311967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb9a4b5d660d'
down_revision = 'd09f31d90362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('native_english_speaker', sa.String(length=100), nullable=True),
    sa.Column('course_instructor', sa.String(length=50), nullable=True),
    sa.Column('course', sa.String(length=200), nullable=True),
    sa.Column('semester', sa.String(length=10), nullable=True),
    sa.Column('class_size', sa.String(length=200), nullable=True),
    sa.Column('performance_score', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=800), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ta')
    # ### end Alembic commands ###
